SELECT			
	UPDATED = D.UPDT_DT_TM "YYYY-MM-DD HH:MM:SS;;D"		
	, TIME_BEG = D.BEG_EFFECTIVE_DT_TM "YYYY-MM-DD HH:MM:SS;;D"		
	, TIME_END = D.END_EFFECTIVE_DT_TM "YYYY-MM-DD HH:MM:SS;;D"		
	, STAFF = PR.NAME_FULL_FORMATTED		
	, PATIENT = PE.NAME_FULL_FORMATTED		
	, PATIENT_ID = D.PERSON_ID
	, MED_SERVICE = uar_get_code_display(P.PCT_MED_SERVICE_CD)		
	, P_PCT_TEAM_DISP = UAR_GET_CODE_DISPLAY(P.PCT_TEAM_CD)		
	, P.BEGIN_EFFECTIVE_DT_TM		
	, P.END_EFFECTIVE_DT_TM		
	, D.ACTIVE_IND		
	, P.ACTIVE_IND		
	, D_LOC_BED_DISP = UAR_GET_CODE_DISPLAY(D.LOC_BED_CD)		
	, D_LOC_BUILDING_DISP = UAR_GET_CODE_DISPLAY(D.LOC_BUILDING_CD)		
	, D_LOC_FACILITY_DISP = UAR_GET_CODE_DISPLAY(D.LOC_FACILITY_CD)		
	, D_LOC_ROOM_DISP = UAR_GET_CODE_DISPLAY(D.LOC_ROOM_CD)		
	, D_LOC_UNIT_DISP = UAR_GET_CODE_DISPLAY(D.LOC_UNIT_CD)		
	, PATIENT_ID_RELATED = D.RELATED_PERSON_ID		
			
FROM			
	DCP_SHIFT_ASSIGNMENT   D		
	, PCT_CARE_TEAM   P		
	, PERSON   PE		
	, PRSNL   PR		
			
PLAN D
/*			
	WHERE		
		'D.UPDT_ID = XXXX	
*/	
	
	WHERE		
		D.UPDT_DT_TM	
		BETWEEN	
			CNVTDATETIME("01-JUL-2022 00:00:00.00")
			AND
			CNVTDATETIME("12-JUL-2022 00:00:00.00")
		
JOIN P WHERE P.PCT_CARE_TEAM_ID = D.PCT_CARE_TEAM_ID			
	
/*			
	AND		
	;P.PRSNL_ID = XXXXX		
	P.UPDT_DT_TM		
		BETWEEN	
			CNVTDATETIME("10-JUL-2022 00:00:00.00")
			AND
			CNVTDATETIME("12-JUL-2022 00:00:00.00")
*/			
			
JOIN PR WHERE PR.PERSON_ID = D.UPDT_ID			
			
JOIN PE WHERE PE.PERSON_ID = D.PERSON_ID			
			
WITH MAXREC = 1000, TIME = 20	