SELECT
	D.DESCRIPTION
	, D.NAME
	, D.OWNER_PRSNL_ID
	, D.PATIENT_LIST_ID
	, D_PATIENT_LIST_TYPE_DISP = UAR_GET_CODE_DISPLAY(D.PATIENT_LIST_TYPE_CD)
	, D.ROWID
	, D.UPDT_APPLCTX
	, D.UPDT_CNT
	, D.UPDT_DT_TM
	, D.UPDT_ID
	, D.UPDT_TASK

FROM
	DCP_PATIENT_LIST   D

WHERE 
	D.NAME = "*RADU*" ; Variable

WITH MAXREC = 1000, NOCOUNTER, SEPARATOR=" ", FORMAT, TIME = 10