SELECT
	O_ACTIVITY_TYPE_DISP = UAR_GET_CODE_DISPLAY(O.ACTIVITY_TYPE_CD)
	, O_CATALOG_DISP = UAR_GET_CODE_DISPLAY(O.CATALOG_CD)
	, O.CATALOG_TYPE_CD
	, O_CATALOG_TYPE_DISP = UAR_GET_CODE_DISPLAY(O.CATALOG_TYPE_CD)
	, O.ENCNTR_ID
	, O.ORDER_ID
	, O_ORDER_STATUS_DISP = UAR_GET_CODE_DISPLAY(O.ORDER_STATUS_CD)
	, O.ORIGINATING_ENCNTR_ID
	, O.ORIG_ORDER_DT_TM
	, O.PERSON_ID
	, P.NAME_FULL_FORMATTED

FROM
	ORDERS   O
	, (LEFT JOIN PERSON P ON (P.PERSON_ID = O.PERSON_ID))

PLAN O WHERE
	(O.ORIG_ORDER_DT_TM BETWEEN 
		CNVTDATETIME("31-DEC-2021 23:59:59.00") 
		AND
		CNVTDATETIME("02-JAN-2022 23:59:59.00")
	)
	AND
	O.CATALOG_TYPE_CD = 2516


JOIN P

WITH MAXREC = 1000, NOCOUNTER, SEPARATOR=" ", FORMAT, TIME = 60