SELECT
/*
This get's all the pharmacy orders for the date range
"01-FEB-2021 00:00:00.00" and "01-AUG-2021 23:59:59.00"
1/2/21-31/7/21 - user wants encounters in this time
 */
	; , O_CATALOG_DISP = UAR_GET_CODE_DISPLAY(O.CATALOG_CD)
	; , O.CATALOG_TYPE_CD
	; , O_CATALOG_TYPE_DISP = UAR_GET_CODE_DISPLAY(O.CATALOG_TYPE_CD)
	O.ENCNTR_ID
	, O.ORDER_ID
    , O.ORDER_STATUS_CD
	, O_ORDER_STATUS_DISP = UAR_GET_CODE_DISPLAY(O.ORDER_STATUS_CD)
	, O.ORIG_ORDER_DT_TM
	, O.PERSON_ID
	, P.NAME_FULL_FORMATTED

FROM
	ORDERS   O
	, (LEFT JOIN PERSON P ON (P.PERSON_ID = O.PERSON_ID))

PLAN O WHERE
	(O.ORIG_ORDER_DT_TM BETWEEN 
		CNVTDATETIME("01-FEB-2021 00:00:00.00")
		AND
		CNVTDATETIME("01-AUG-2021 23:59:59.00")
	) ; Date range filter above
	AND
	O.CATALOG_TYPE_CD = 2516 ; Filters for only 'Pharmacy'
    AND
    O.ORDER_STATUS_CD = 2543 ; Filters for only 'Completed' order status'


JOIN P

WITH NOCOUNTER, SEPARATOR=" ", FORMAT, TIME = 600